# Generated by Django 5.0.7 on 2025-03-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the place.', max_length=255, unique=True, verbose_name='Name of the place')),
                ('category', models.CharField(choices=[('restaurant', 'Restaurant'), ('store', 'Store'), ('cafe', 'Cafe'), ('service', 'Service'), ('other', 'Other')], help_text='Select the category of the place.', max_length=100, verbose_name='Category')),
                ('address', models.CharField(help_text='Enter the address of the place.', max_length=500, verbose_name='Address')),
                ('phone_number', models.CharField(blank=True, help_text='Enter the phone number of the place.', max_length=15, null=True, verbose_name='Phone number')),
                ('website', models.URLField(blank=True, help_text='Enter the website of the place.', null=True, verbose_name='Website')),
                ('description', models.TextField(blank=True, help_text='Write a description of the place.', null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, help_text='Upload an image of the place.', null=True, upload_to='places/', verbose_name='Place Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
            },
        ),
    ]
