# Generated by Django 5.0.7 on 2025-03-14 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='created_at',
            new_name='datetime_created',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='updated_at',
            new_name='datetime_updated',
        ),
        migrations.RemoveField(
            model_name='place',
            name='image',
        ),
        migrations.RemoveField(
            model_name='place',
            name='name',
        ),
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.CharField(choices=[('Berlin', 'Berlin'), ('Hamburg', 'Hamburg'), ('München', 'München'), ('Köln', 'Köln'), ('Frankfurt am Main', 'Frankfurt am Main'), ('Stuttgart', 'Stuttgart'), ('Düsseldorf', 'Düsseldorf'), ('Dortmund', 'Dortmund'), ('Essen', 'Essen'), ('Leipzig', 'Leipzig'), ('Bremen', 'Bremen'), ('Dresden', 'Dresden'), ('Hannover', 'Hannover'), ('Nürnberg', 'Nürnberg'), ('Duisburg', 'Duisburg'), ('Bochum', 'Bochum'), ('Wuppertal', 'Wuppertal'), ('Bielefeld', 'Bielefeld'), ('Bonn', 'Bonn'), ('Münster', 'Münster'), ('Karlsruhe', 'Karlsruhe'), ('Mannheim', 'Mannheim'), ('Augsburg', 'Augsburg'), ('Wiesbaden', 'Wiesbaden'), ('Mönchengladbach', 'Mönchengladbach'), ('Gelsenkirchen', 'Gelsenkirchen'), ('Braunschweig', 'Braunschweig'), ('Chemnitz', 'Chemnitz'), ('Kiel', 'Kiel'), ('Aachen', 'Aachen'), ('Halle (Saale)', 'Halle (Saale)'), ('Magdeburg', 'Magdeburg'), ('Freiburg im Breisgau', 'Freiburg im Breisgau'), ('Krefeld', 'Krefeld'), ('Lübeck', 'Lübeck'), ('Oberhausen', 'Oberhausen'), ('Erfurt', 'Erfurt'), ('Mainz', 'Mainz'), ('Rostock', 'Rostock'), ('Kassel', 'Kassel'), ('Hagen', 'Hagen'), ('Hamm', 'Hamm'), ('Saarbrücken', 'Saarbrücken'), ('Mülheim an der Ruhr', 'Mülheim an der Ruhr'), ('Potsdam', 'Potsdam'), ('Ludwigshafen am Rhein', 'Ludwigshafen am Rhein'), ('Oldenburg', 'Oldenburg'), ('Leverkusen', 'Leverkusen'), ('Osnabrück', 'Osnabrück'), ('Solingen', 'Solingen'), ('Heidelberg', 'Heidelberg'), ('Herne', 'Herne'), ('Neuss', 'Neuss'), ('Darmstadt', 'Darmstadt'), ('Paderborn', 'Paderborn'), ('Regensburg', 'Regensburg'), ('Ingolstadt', 'Ingolstadt'), ('Würzburg', 'Würzburg'), ('Fürth', 'Fürth'), ('Wolfsburg', 'Wolfsburg'), ('Offenbach am Main', 'Offenbach am Main'), ('Ulm', 'Ulm'), ('Heilbronn', 'Heilbronn'), ('Pforzheim', 'Pforzheim'), ('Göttingen', 'Göttingen'), ('Bottrop', 'Bottrop'), ('Trier', 'Trier'), ('Recklinghausen', 'Recklinghausen'), ('Reutlingen', 'Reutlingen'), ('Bremerhaven', 'Bremerhaven'), ('Koblenz', 'Koblenz'), ('Bergisch Gladbach', 'Bergisch Gladbach'), ('Jena', 'Jena'), ('Remscheid', 'Remscheid'), ('Erlangen', 'Erlangen'), ('Moers', 'Moers'), ('Siegen', 'Siegen'), ('Hildesheim', 'Hildesheim'), ('Salzgitter', 'Salzgitter')], default='Berlin', max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='image1',
            field=models.ImageField(blank=True, help_text='Upload an image 1 of the place.', null=True, upload_to='places/', verbose_name='Place Image'),
        ),
        migrations.AddField(
            model_name='place',
            name='image2',
            field=models.ImageField(blank=True, help_text='Upload an image 2 of the place.', null=True, upload_to='places/', verbose_name='Place Image'),
        ),
        migrations.AddField(
            model_name='place',
            name='image3',
            field=models.ImageField(blank=True, help_text='Upload an image 3 of the place.', null=True, upload_to='places/', verbose_name='Place Image'),
        ),
        migrations.AddField(
            model_name='place',
            name='image4',
            field=models.ImageField(blank=True, help_text='Upload an image 4 of the place.', null=True, upload_to='places/', verbose_name='Place Image'),
        ),
        migrations.AddField(
            model_name='place',
            name='image5',
            field=models.ImageField(blank=True, help_text='Upload an image 5 of the place.', null=True, upload_to='places/', verbose_name='Place Image'),
        ),
        migrations.AddField(
            model_name='place',
            name='title',
            field=models.CharField(blank=True, help_text='Enter the name of the place.', max_length=250, null=True, unique=True, verbose_name='Name of the place'),
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, help_text='Enter the address of the place.', max_length=500, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('Food and Drink', 'Food and Drink'), ('medical services', 'Medical services'), ('technical services', 'Technical services'), ('store', 'Store'), ('entertainment', 'Entertainment'), ('other', 'Other')], help_text='Select the category of the place.', max_length=100, verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Write your comment here.', max_length=500, verbose_name='Description')),
                ('opinion', models.CharField(choices=[('perfect', 'Perfect'), ('good', 'Good'), ('weak', 'Weak')], max_length=50)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='places.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
