# Generated by Django 5.0.7 on 2025-03-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_rename_created_at_place_datetime_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(help_text='Enter the address of the place.', max_length=500, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(help_text='Write a description of the place.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(help_text='Enter the name of the place.', max_length=250, unique=True, verbose_name='Name of the place'),
        ),
    ]
