# Generated by Django 5.0.7 on 2025-03-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_address_alter_place_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('food and Drink', 'Food and Drink'), ('medical services', 'Medical services'), ('technical services', 'Technical services'), ('store', 'Store'), ('entertainment', 'Entertainment'), ('other', 'Other')], help_text='Select the category of the place.', max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image1',
            field=models.ImageField(blank=True, help_text='Upload an image 1 of the place.', null=True, upload_to='places/', verbose_name='Place Image1'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image2',
            field=models.ImageField(blank=True, help_text='Upload an image 2 of the place.', null=True, upload_to='places/', verbose_name='Place Image2'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image3',
            field=models.ImageField(blank=True, help_text='Upload an image 3 of the place.', null=True, upload_to='places/', verbose_name='Place Image3'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image4',
            field=models.ImageField(blank=True, help_text='Upload an image 4 of the place.', null=True, upload_to='places/', verbose_name='Place Image4'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image5',
            field=models.ImageField(blank=True, help_text='Upload an image 5 of the place.', null=True, upload_to='places/', verbose_name='Place Image5'),
        ),
    ]
