# Generated by Django 5.0.7 on 2025-03-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_place_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='image1',
        ),
        migrations.AddField(
            model_name='place',
            name='image_main',
            field=models.ImageField(blank=True, help_text='Upload an main image of the place or service.', null=True, upload_to='places/', verbose_name='Main Image'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image2',
            field=models.ImageField(blank=True, help_text='Upload an image 2 of the place or service.', null=True, upload_to='places/', verbose_name='Image2'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image3',
            field=models.ImageField(blank=True, help_text='Upload an image 3 of the place or service.', null=True, upload_to='places/', verbose_name='Image3'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image4',
            field=models.ImageField(blank=True, help_text='Upload an image 4 of the place or service.', null=True, upload_to='places/', verbose_name='Image4'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image5',
            field=models.ImageField(blank=True, help_text='Upload an image 5 of the place or service.', null=True, upload_to='places/', verbose_name='Image5'),
        ),
    ]
