# Generated by Django 5.0.7 on 2025-03-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_remove_place_image1_place_image_main_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='opinion',
        ),
        migrations.AddField(
            model_name='comment',
            name='user_rating',
            field=models.CharField(choices=[('perfect', 'Perfect'), ('good', 'Good'), ('weak', 'Weak'), ('too bad', 'Too bad')], default='good', max_length=50),
            preserve_default=False,
        ),
    ]
