# Generated by Django 5.0.7 on 2025-03-17 19:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_remove_comment_opinion_comment_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
    ]
