# Generated by Django 5.0.7 on 2025-03-18 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_comment_datetime_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['datetime_created']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_rating',
            field=models.CharField(choices=[('perfect', 'Perfect'), ('good', 'Good'), ('weak', 'Weak'), ('too bad', 'Too bad')], max_length=50, verbose_name='Rating'),
        ),
    ]
