# Generated by Django 5.0.7 on 2025-03-18 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_alter_comment_options_alter_comment_user_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
