# Generated by Django 5.0.7 on 2025-03-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(max_length=500, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('food & drink', 'Food & Drink'), ('medical', 'Medical'), ('technical', 'Technical'), ('store', 'Store'), ('entertainment', 'Entertainment'), ('other', 'Other')], max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='places/', verbose_name='Image2'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='places/', verbose_name='Image3'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='places/', verbose_name='Image4'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='places/', verbose_name='Image5'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image_main',
            field=models.ImageField(blank=True, null=True, upload_to='places/', verbose_name='Main Image'),
        ),
        migrations.AlterField(
            model_name='place',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=250, unique=True, verbose_name='Name of the place'),
        ),
        migrations.AlterField(
            model_name='place',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
