# Generated by Django 5.0.7 on 2025-03-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_alter_place_address_alter_place_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(choices=[('Berlin', 'Berlin'), ('Hamburg', 'Hamburg'), ('München', 'München'), ('Köln', 'Köln'), ('Frankfurt am Main', 'Frankfurt am Main'), ('Stuttgart', 'Stuttgart'), ('Düsseldorf', 'Düsseldorf'), ('Dortmund', 'Dortmund'), ('Essen', 'Essen'), ('Leipzig', 'Leipzig'), ('Bremen', 'Bremen'), ('Dresden', 'Dresden'), ('Hannover', 'Hannover'), ('Nürnberg', 'Nürnberg'), ('Duisburg', 'Duisburg'), ('Bochum', 'Bochum'), ('Wuppertal', 'Wuppertal'), ('Bielefeld', 'Bielefeld'), ('Bonn', 'Bonn'), ('Münster', 'Münster'), ('Karlsruhe', 'Karlsruhe'), ('Mannheim', 'Mannheim'), ('Augsburg', 'Augsburg'), ('Wiesbaden', 'Wiesbaden'), ('Mönchengladbach', 'Mönchengladbach'), ('Gelsenkirchen', 'Gelsenkirchen'), ('Braunschweig', 'Braunschweig'), ('Chemnitz', 'Chemnitz'), ('Kiel', 'Kiel'), ('Aachen', 'Aachen'), ('Halle (Saale)', 'Halle (Saale)'), ('Magdeburg', 'Magdeburg'), ('Freiburg im Breisgau', 'Freiburg im Breisgau'), ('Krefeld', 'Krefeld'), ('Lübeck', 'Lübeck'), ('Oberhausen', 'Oberhausen'), ('Erfurt', 'Erfurt'), ('Mainz', 'Mainz'), ('Rostock', 'Rostock'), ('Kassel', 'Kassel'), ('Hagen', 'Hagen'), ('Hamm', 'Hamm'), ('Saarbrücken', 'Saarbrücken'), ('Mülheim an der Ruhr', 'Mülheim an der Ruhr'), ('Potsdam', 'Potsdam'), ('Ludwigshafen am Rhein', 'Ludwigshafen am Rhein'), ('Oldenburg', 'Oldenburg'), ('Leverkusen', 'Leverkusen'), ('Osnabrück', 'Osnabrück'), ('Solingen', 'Solingen'), ('Heidelberg', 'Heidelberg'), ('Herne', 'Herne'), ('Neuss', 'Neuss'), ('Darmstadt', 'Darmstadt'), ('Paderborn', 'Paderborn'), ('Regensburg', 'Regensburg'), ('Ingolstadt', 'Ingolstadt'), ('Würzburg', 'Würzburg'), ('Fürth', 'Fürth'), ('Wolfsburg', 'Wolfsburg'), ('Offenbach am Main', 'Offenbach am Main'), ('Ulm', 'Ulm'), ('Heilbronn', 'Heilbronn'), ('Pforzheim', 'Pforzheim'), ('Göttingen', 'Göttingen'), ('Bottrop', 'Bottrop'), ('Trier', 'Trier'), ('Recklinghausen', 'Recklinghausen'), ('Reutlingen', 'Reutlingen'), ('Bremerhaven', 'Bremerhaven'), ('Koblenz', 'Koblenz'), ('Bergisch Gladbach', 'Bergisch Gladbach'), ('Jena', 'Jena'), ('Remscheid', 'Remscheid'), ('Erlangen', 'Erlangen'), ('Moers', 'Moers'), ('Siegen', 'Siegen'), ('Hildesheim', 'Hildesheim'), ('Salzgitter', 'Salzgitter')], default='Berlin', max_length=100, verbose_name='City'),
        ),
    ]
