# Generated by Django 5.0.7 on 2025-03-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_alter_place_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='status',
            field=models.CharField(choices=[('pub', 'Published'), ('drf', 'Draft')], default='drf', max_length=3, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=250, unique=True, verbose_name='Name of the place or service'),
        ),
    ]
