# Generated by Django 5.0.7 on 2025-03-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0016_place_status_alter_place_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Name of the place or service'),
        ),
    ]
