# Generated by Django 5.0.7 on 2025-03-19 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0017_alter_place_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='website',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Website'),
        ),
    ]
