# Generated by Django 5.0.7 on 2025-03-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0018_alter_place_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
