# Generated by Django 5.0.7 on 2025-03-14 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='favorite_places',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='reported_places',
        ),
    ]
