# Generated by Django 5.0.7 on 2025-03-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_favorite_places_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='accounts/profile_default.jpg', null=True, upload_to='profile_pics/', verbose_name='Profile photo'),
        ),
    ]
