# Generated by Django 5.0.7 on 2025-03-18 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_profile_pic'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='customuser_groups', to='auth.group', verbose_name='Groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='Is Banned?'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='total_reports',
            field=models.IntegerField(default=0, verbose_name='Total Reports'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='total_reviews',
            field=models.IntegerField(default=0, verbose_name='Total Reviews'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='customuser_permissions', to='auth.permission', verbose_name='User Permissions'),
        ),
    ]
